spring:
  profiles: dev
server:
  port: 8000
---
spring:
  profiles: test
server:
  port: 9000

  




#spring.data.mongodb.host=127.0.0.1
##spring.data.mongodb.host=192.168.0.2
##spring.data.mongodb.port=27017
##spring.data.mongodb.authentication-database=reuniaoinfotm
#spring.data.mongodb.username=mongoJavaConn
#spring.data.mongodb.password=mongoDB15347
##spring.data.mongodb.database=reuniaoinfotm
#spring.data.mongodb.repositories.enabled=true

#spring.data.mongodb.host=192.168.0.2
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=reuniaoinfotm
#spring.data.mongodb.uri=mongodb://mongoJavaConn:mongoDB15347@192.168.0.2:27017?authenticationDatabase=reuniaoinfotm
#spring.data.mongodb.uri=mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test

#spring.profiles: integration
# use local or embedded mongodb at localhost:27017
#---
#spring.profiles: production
#spring.data.mongodb.uri: mongodb://<user>:<passwd>@<url>:<port>/<dbname>

#spring.data.mongodb.uri=mongodb://mongoJavaConn:@MongoDBJavaConn1914@localhost:27017

#spring.data.mongodb.authentication-database= # Authentication database name.
#spring.data.mongodb.field-naming-strategy= # Fully qualified name of the FieldNamingStrategy to use.
#spring.data.mongodb.grid-fs-database= # GridFS database name.
#spring.data.mongodb.host=localhost
#spring.data.mongodb.password=@MongoDBJavaConn1914
#spring.data.mongodb.port=27017
#spring.data.mongodb.repositories.enabled=true

#spring.data.mongodb.uri=mongodb://mongoJavaConn:%40MongoDBJavaConn1914@192.168.0.2:27017

#spring.data.mongodb.username=mongoJavaConn

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.continue-on-error=true